import type {
  AppData,
  Person,
  TemplateDef,
  Thread,
  ActionItem,
  AsyncItem,
  MeetingRecord,
} from "../domain/types";

const TEMPLATES: TemplateDef[] = [
  {
    id: "growth",
    name: "Career & growth",
    primaryArea: "growth",
    prompts: [
      "Where do you want to be in 12 months?",
      "What would unblock your next step?",
      "What growth feels stalled?",
    ],
  },
  {
    id: "feedback",
    name: "Feedback exchange",
    primaryArea: "feedback",
    prompts: [
      "What feedback do you have for me?",
      "One thing going well, one to adjust",
      "How did recent feedback land?",
    ],
  },
  {
    id: "deep-dive",
    name: "Project deep-dive",
    primaryArea: "workload",
    prompts: [
      "Walk me through the current state",
      "Where are the risks?",
      "What decision do you need from me?",
    ],
  },
  {
    id: "skip",
    name: "Skip-level prep",
    primaryArea: "relationships",
    prompts: [
      "What should leadership hear?",
      "What's working across the team?",
      "Anything you can't raise elsewhere?",
    ],
  },
  {
    id: "checkin",
    name: "Light check-in",
    primaryArea: "wellbeing",
    prompts: [
      "How are you, really?",
      "What's draining energy?",
      "What would make next week better?",
    ],
  },
];

// ---------------------------------------------------------------------------
// Sofia Marchetti — Staff Engineer; on track; back from parental leave soon;
// healthy report-led balance; 1 async from her.
// ---------------------------------------------------------------------------
const sofia: Person = {
  id: "p-sofia",
  name: "Sofia Marchetti",
  role: "Staff Engineer",
  pronouns: "she/her",
  initials: "SM",
  hue: 210,
  tenureMonths: 38,
  cadenceDays: 14,
  lastOneOnOne: "2026-05-22",
  nextScheduled: "2026-06-05",
  talkTrend: [62, 58, 65, 70, 68],
  sentimentTrend: [4, 4, 5, 4, 5],
  coverage: {
    growth: 12,
    feedback: 8,
    workload: 5,
    wellbeing: 14,
    relationships: 14,
    recognition: 22,
  },
  threads: [
    {
      id: "t-sofia-1",
      title: "Staff IC track after parental leave",
      area: "growth",
      status: "open",
      priority: 72,
      lastTouched: "2026-05-22",
      note: "She's thinking about scope changes on return. Worth revisiting expectations.",
      raise: true,
    },
    {
      id: "t-sofia-2",
      title: "Architecture ownership of the auth service",
      area: "workload",
      status: "open",
      priority: 55,
      lastTouched: "2026-05-08",
      note: "She volunteered to own this before leave — confirm still the plan.",
      raise: false,
    },
  ],
  actions: [
    {
      id: "a-sofia-1",
      text: "Confirm ramp-back plan with HR before Sofia's return",
      owner: "manager",
      status: "open",
      createdAt: "2026-05-22",
      fromArea: "wellbeing",
    },
    {
      id: "a-sofia-2",
      text: "Share updated team context doc before return",
      owner: "manager",
      status: "open",
      createdAt: "2026-05-22",
      fromArea: "relationships",
    },
    {
      id: "a-sofia-3",
      text: "Review auth service RFC draft",
      owner: "report",
      status: "done",
      createdAt: "2026-04-30",
      doneAt: "2026-05-10",
      fromArea: "workload",
    },
  ],
  asyncAgenda: [
    {
      id: "async-sofia-1",
      text: "Thinking about what 'on-call' looks like for me when I'm back — want to align before my first week.",
      area: "workload",
      mood: "neutral",
      addedAt: "2026-05-28",
    },
  ],
  meetings: [
    {
      date: "2026-03-13",
      durationMin: 30,
      reportShare: 62,
      areas: ["growth", "workload"],
      actions: 2,
      summary: "Discussed staff-level scope. Auth service RFC on the horizon.",
    },
    {
      date: "2026-03-27",
      durationMin: 30,
      reportShare: 58,
      areas: ["feedback", "workload"],
      actions: 1,
      summary: "Pre-leave feedback exchange. Good two-way conversation.",
    },
    {
      date: "2026-04-10",
      durationMin: 30,
      reportShare: 65,
      areas: ["wellbeing", "growth"],
      actions: 2,
      summary: "Leave prep. Sofia is excited and a bit anxious.",
    },
    {
      date: "2026-04-25",
      durationMin: 30,
      reportShare: 70,
      areas: ["workload", "relationships"],
      actions: 1,
      summary: "Handoff session — handed auth ownership to Tariq temporarily.",
    },
    {
      date: "2026-05-22",
      durationMin: 30,
      reportShare: 68,
      areas: ["wellbeing", "growth", "recognition"],
      actions: 2,
      summary: "Check-in before leave starts. Sofia feeling good. Flagged promo timeline question.",
    },
  ],
};

// ---------------------------------------------------------------------------
// Priya Raman — Engineering Manager; due soon; carrying two open roles;
// recognition cold.
// ---------------------------------------------------------------------------
const priya: Person = {
  id: "p-priya",
  name: "Priya Raman",
  role: "Engineering Manager",
  pronouns: "she/her",
  initials: "PR",
  hue: 290,
  tenureMonths: 22,
  cadenceDays: 14,
  lastOneOnOne: "2026-05-16",
  nextScheduled: "2026-06-06",
  talkTrend: [48, 52, 44, 50, 47],
  sentimentTrend: [3, 3, 4, 3, 3],
  coverage: {
    growth: 18,
    feedback: 16,
    workload: 9,
    wellbeing: 18,
    relationships: 25,
    recognition: 41,
  },
  threads: [
    {
      id: "t-priya-1",
      title: "Two open roles stretching her team thin",
      area: "workload",
      status: "open",
      priority: 80,
      lastTouched: "2026-05-16",
      note: "She's running sprint ceremonies AND covering senior IC work. Burnout risk.",
      raise: true,
    },
    {
      id: "t-priya-2",
      title: "No time for her own IC contribution in Q2",
      area: "growth",
      status: "open",
      priority: 60,
      lastTouched: "2026-05-02",
      note: "She mentioned this briefly. Worth a real conversation.",
      raise: false,
    },
    {
      id: "t-priya-3",
      title: "Recognition gap — wins not being surfaced",
      area: "recognition",
      status: "open",
      priority: 65,
      lastTouched: "2026-04-18",
      note: "Her team shipped two big things with zero fanfare. She noticed.",
      raise: false,
    },
  ],
  actions: [
    {
      id: "a-priya-1",
      text: "Push headcount request to VP of Eng this week",
      owner: "manager",
      status: "open",
      createdAt: "2026-05-16",
      fromArea: "workload",
      linkedThread: "t-priya-1",
    },
    {
      id: "a-priya-2",
      text: "Write up Q2 wins for leadership update",
      owner: "manager",
      status: "open",
      createdAt: "2026-05-02",
      fromArea: "recognition",
      linkedThread: "t-priya-3",
    },
    {
      id: "a-priya-3",
      text: "Draft interview loop for senior backend role",
      owner: "report",
      status: "open",
      createdAt: "2026-05-16",
      fromArea: "workload",
    },
    {
      id: "a-priya-4",
      text: "Send thank-you note to Priya for covering on-call gap",
      owner: "manager",
      status: "done",
      createdAt: "2026-05-09",
      doneAt: "2026-05-10",
      fromArea: "recognition",
    },
  ],
  asyncAgenda: [
    {
      id: "async-priya-1",
      text: "The two open reqs are moving too slowly. I need to understand the hiring freeze timeline before I can plan.",
      area: "workload",
      mood: "unsure",
      addedAt: "2026-05-29",
    },
  ],
  meetings: [
    {
      date: "2026-03-06",
      durationMin: 30,
      reportShare: 48,
      areas: ["workload", "relationships"],
      actions: 2,
      summary: "Staffing gap surfaced. She's juggling IC work again.",
    },
    {
      date: "2026-03-20",
      durationMin: 30,
      reportShare: 52,
      areas: ["feedback", "growth"],
      actions: 1,
      summary: "Positive feedback exchange. Growth goals unclear for the year.",
    },
    {
      date: "2026-04-03",
      durationMin: 30,
      reportShare: 44,
      areas: ["workload", "wellbeing"],
      actions: 3,
      summary: "Headcount urgency escalated. Signs of stress.",
    },
    {
      date: "2026-04-18",
      durationMin: 30,
      reportShare: 50,
      areas: ["recognition", "relationships"],
      actions: 1,
      summary: "Team wins debrief. Recognition clearly missing.",
    },
    {
      date: "2026-05-16",
      durationMin: 30,
      reportShare: 47,
      areas: ["workload", "growth"],
      actions: 2,
      summary: "Headcount push agreed. IC time is zero — needs relief.",
    },
  ],
};

// ---------------------------------------------------------------------------
// Tariq Hassan — Member of Technical Staff; energy low; wellbeing stale;
// stressed async item; open loops overdue.
// ---------------------------------------------------------------------------
const tariq: Person = {
  id: "p-tariq",
  name: "Tariq Hassan",
  role: "Member of Technical Staff",
  pronouns: "he/him",
  initials: "TH",
  hue: 30,
  tenureMonths: 14,
  cadenceDays: 7,
  lastOneOnOne: "2026-05-27",
  nextScheduled: "2026-06-03",
  talkTrend: [40, 38, 35, 42, 38],
  sentimentTrend: [3, 3, 2, 2, 2],
  coverage: {
    growth: 14,
    feedback: 21,
    workload: 7,
    wellbeing: 37,
    relationships: 28,
    recognition: 30,
  },
  threads: [
    {
      id: "t-tariq-1",
      title: "Energy and motivation seem lower than usual",
      area: "wellbeing",
      status: "open",
      priority: 88,
      lastTouched: "2026-05-27",
      note: "He's been quieter in standups, shipping slower. Not burning out yet but worth naming.",
      raise: true,
    },
    {
      id: "t-tariq-2",
      title: "Unclear path from MTS to Staff",
      area: "growth",
      status: "open",
      priority: 55,
      lastTouched: "2026-05-13",
      note: "He mentioned the gap in expectations. No formal ladder conversation had yet.",
      raise: false,
    },
    {
      id: "t-tariq-3",
      title: "Temporarily covering auth service for Sofia",
      area: "workload",
      status: "parked",
      priority: 40,
      lastTouched: "2026-04-25",
      note: "Agreed as a short-term cover. Parked — revisit when Sofia is back.",
      raise: false,
    },
  ],
  actions: [
    {
      id: "a-tariq-1",
      text: "Have an explicit wellbeing check-in — create safe space to surface what's going on",
      owner: "manager",
      status: "open",
      createdAt: "2026-05-06",
      fromArea: "wellbeing",
      linkedThread: "t-tariq-1",
    },
    {
      id: "a-tariq-2",
      text: "Share Staff-level expectations doc and schedule a career chat",
      owner: "manager",
      status: "open",
      createdAt: "2026-05-13",
      fromArea: "growth",
      linkedThread: "t-tariq-2",
    },
    {
      id: "a-tariq-3",
      text: "Write up auth service coverage notes for Sofia's return",
      owner: "report",
      status: "open",
      createdAt: "2026-04-25",
      fromArea: "workload",
    },
  ],
  asyncAgenda: [
    {
      id: "async-tariq-1",
      text: "Honestly feeling a bit stuck and drained lately. Not sure what's driving it but I wanted you to know.",
      area: "wellbeing",
      mood: "stressed",
      addedAt: "2026-05-30",
    },
    {
      id: "async-tariq-2",
      text: "Had a rough PR review last week. The feedback felt harsh. Want to talk through it.",
      area: "feedback",
      mood: "unsure",
      addedAt: "2026-06-01",
    },
  ],
  meetings: [
    {
      date: "2026-04-15",
      durationMin: 30,
      reportShare: 40,
      areas: ["workload", "growth"],
      actions: 1,
      summary: "Good pace on auth cover. Growth path not yet named.",
    },
    {
      date: "2026-04-22",
      durationMin: 30,
      reportShare: 38,
      areas: ["feedback", "workload"],
      actions: 2,
      summary: "Feedback on recent work — positive but delivery style came up.",
    },
    {
      date: "2026-04-29",
      durationMin: 30,
      reportShare: 35,
      areas: ["wellbeing", "relationships"],
      actions: 1,
      summary: "First hint of low energy. Wellbeing flag raised internally.",
    },
    {
      date: "2026-05-13",
      durationMin: 30,
      reportShare: 42,
      areas: ["growth", "feedback"],
      actions: 2,
      summary: "Career chat started. Staff bar discussed briefly.",
    },
    {
      date: "2026-05-27",
      durationMin: 30,
      reportShare: 38,
      areas: ["workload", "wellbeing"],
      actions: 2,
      summary: "Tariq quieter than usual. Wellbeing flagged explicitly.",
    },
  ],
};

// ---------------------------------------------------------------------------
// Maya Lindqvist — Senior Product Designer; deep-dive subject;
// relationships not touched in 47 days; specific threads and async items.
// ---------------------------------------------------------------------------
const maya: Person = {
  id: "p-maya",
  name: "Maya Lindqvist",
  role: "Senior Product Designer",
  pronouns: "she/her",
  initials: "ML",
  hue: 165,
  tenureMonths: 31,
  cadenceDays: 14,
  lastOneOnOne: "2026-05-20",
  nextScheduled: "2026-06-10",
  talkTrend: [55, 60, 58, 65, 22],
  sentimentTrend: [4, 4, 3, 4, 3],
  coverage: {
    growth: 14,
    feedback: 20,
    workload: 10,
    wellbeing: 22,
    relationships: 47,
    recognition: 30,
  },
  threads: [
    {
      id: "t-maya-1",
      title: "Friction with the platform pod",
      area: "relationships",
      status: "open",
      priority: 85,
      lastTouched: "2026-05-20",
      note: "Maya says the platform team keeps overriding design decisions in sprint. Feeling unheard.",
      raise: true,
    },
    {
      id: "t-maya-2",
      title: "Staff designer track",
      area: "growth",
      status: "open",
      priority: 78,
      lastTouched: "2026-05-06",
      note: "She wants to understand the bar — what does 'staff' look like for an IC designer here?",
      raise: true,
    },
    {
      id: "t-maya-3",
      title: "Onboarding revamp launch",
      area: "workload",
      status: "open",
      priority: 65,
      lastTouched: "2026-05-20",
      note: "Launch was delayed a week. She owns the design system side.",
      raise: false,
    },
    {
      id: "t-maya-4",
      title: "Design review process needs clarity",
      area: "feedback",
      status: "parked",
      priority: 40,
      lastTouched: "2026-04-15",
      note: "Process question — parked until after onboarding launch.",
      raise: false,
    },
  ],
  actions: [
    {
      id: "a-maya-1",
      text: "Broker a sync between Maya and the platform pod lead",
      owner: "manager",
      status: "open",
      createdAt: "2026-05-20",
      fromArea: "relationships",
      linkedThread: "t-maya-1",
    },
    {
      id: "a-maya-2",
      text: "Share staff IC design criteria document with Maya",
      owner: "manager",
      status: "open",
      createdAt: "2026-05-06",
      fromArea: "growth",
      linkedThread: "t-maya-2",
    },
    {
      id: "a-maya-3",
      text: "Finish component audit for onboarding revamp",
      owner: "report",
      status: "open",
      createdAt: "2026-05-20",
      fromArea: "workload",
      linkedThread: "t-maya-3",
    },
    {
      id: "a-maya-4",
      text: "Draft design review SLA proposal",
      owner: "report",
      status: "open",
      createdAt: "2026-04-15",
      fromArea: "feedback",
      linkedThread: "t-maya-4",
    },
  ],
  asyncAgenda: [
    {
      id: "async-maya-1",
      text: "Want to talk through the staff promo timeline — feeling some urgency.",
      area: "growth",
      mood: "unsure",
      addedAt: "2026-05-28",
    },
    {
      id: "async-maya-2",
      text: "The platform sync last sprint was rough. I keep getting overruled and I don't know how to handle it.",
      area: "relationships",
      mood: "stressed",
      addedAt: "2026-06-01",
    },
    {
      id: "async-maya-3",
      text: "Onboarding launch is June 17. Still on track but I want to flag a dependency on platform.",
      area: "workload",
      mood: "neutral",
      addedAt: "2026-06-02",
    },
  ],
  meetings: [
    {
      date: "2026-03-10",
      durationMin: 30,
      reportShare: 55,
      areas: ["workload", "growth"],
      actions: 2,
      summary: "Onboarding revamp scoped. Growth ambitions clear.",
    },
    {
      date: "2026-03-24",
      durationMin: 30,
      reportShare: 60,
      areas: ["feedback", "relationships"],
      actions: 1,
      summary: "Platform friction first mention. Feedback on process gaps.",
    },
    {
      date: "2026-04-07",
      durationMin: 45,
      reportShare: 58,
      areas: ["growth", "feedback"],
      actions: 2,
      summary: "Staff track conversation started. Design review process surfaced.",
    },
    {
      date: "2026-04-22",
      durationMin: 30,
      reportShare: 65,
      areas: ["workload", "wellbeing"],
      actions: 1,
      summary: "Onboarding timeline tightening. She's managing well.",
    },
    {
      date: "2026-05-06",
      durationMin: 30,
      reportShare: 60,
      areas: ["growth", "feedback"],
      actions: 2,
      summary: "Staff criteria discussed. Review process parked.",
    },
    {
      date: "2026-05-20",
      durationMin: 30,
      reportShare: 22,
      areas: ["workload", "relationships"],
      actions: 2,
      summary: "Platform pod friction escalated. Brokering a sync. Manager-heavy session.",
    },
  ],
};

// ---------------------------------------------------------------------------
// Dev Okafor — Backend Engineer; hasn't had a real win called out;
// recognition cold; solid performer going unacknowledged.
// ---------------------------------------------------------------------------
const dev: Person = {
  id: "p-dev",
  name: "Dev Okafor",
  role: "Backend Engineer",
  pronouns: "they/them",
  initials: "DO",
  hue: 45,
  tenureMonths: 18,
  cadenceDays: 14,
  lastOneOnOne: "2026-05-20",
  nextScheduled: "2026-06-03",
  talkTrend: [50, 55, 52, 48, 53],
  sentimentTrend: [4, 4, 4, 3, 4],
  coverage: {
    growth: 24,
    feedback: 18,
    workload: 14,
    wellbeing: 28,
    relationships: 32,
    recognition: 44,
  },
  threads: [
    {
      id: "t-dev-1",
      title: "No formal recognition for the billing refactor",
      area: "recognition",
      status: "open",
      priority: 78,
      lastTouched: "2026-05-20",
      note: "Dev shipped a major refactor under the radar. It saved us two incidents. No shoutout, no note to leadership.",
      raise: true,
    },
    {
      id: "t-dev-2",
      title: "Interested in leading a cross-team initiative",
      area: "growth",
      status: "open",
      priority: 62,
      lastTouched: "2026-05-06",
      note: "Dev wants more scope. Billing refactor is proof they can handle it.",
      raise: false,
    },
    {
      id: "t-dev-3",
      title: "On-call load feels asymmetric",
      area: "workload",
      status: "open",
      priority: 50,
      lastTouched: "2026-04-22",
      note: "They're covering more than their share. Needs a fair rotation audit.",
      raise: false,
    },
  ],
  actions: [
    {
      id: "a-dev-1",
      text: "Send leadership note recognizing the billing refactor impact",
      owner: "manager",
      status: "open",
      createdAt: "2026-05-06",
      fromArea: "recognition",
      linkedThread: "t-dev-1",
    },
    {
      id: "a-dev-2",
      text: "Identify a cross-team initiative Dev can lead in Q3",
      owner: "manager",
      status: "open",
      createdAt: "2026-05-20",
      fromArea: "growth",
      linkedThread: "t-dev-2",
    },
    {
      id: "a-dev-3",
      text: "Audit on-call rotation logs and propose rebalance",
      owner: "report",
      status: "open",
      createdAt: "2026-04-22",
      fromArea: "workload",
    },
    {
      id: "a-dev-4",
      text: "Document billing refactor architecture decisions",
      owner: "report",
      status: "done",
      createdAt: "2026-04-30",
      doneAt: "2026-05-14",
      fromArea: "workload",
    },
  ],
  asyncAgenda: [
    {
      id: "async-dev-1",
      text: "I'd love to know if the billing work landed well. Haven't heard much.",
      area: "recognition",
      mood: "neutral",
      addedAt: "2026-05-27",
    },
  ],
  meetings: [
    {
      date: "2026-03-17",
      durationMin: 30,
      reportShare: 50,
      areas: ["workload", "feedback"],
      actions: 1,
      summary: "Billing refactor underway. Good energy.",
    },
    {
      date: "2026-04-01",
      durationMin: 30,
      reportShare: 55,
      areas: ["growth", "relationships"],
      actions: 2,
      summary: "Scope ambitions discussed. On-call gap flagged.",
    },
    {
      date: "2026-04-22",
      durationMin: 30,
      reportShare: 52,
      areas: ["workload", "wellbeing"],
      actions: 2,
      summary: "Refactor shipped. On-call audit planned.",
    },
    {
      date: "2026-05-06",
      durationMin: 30,
      reportShare: 48,
      areas: ["recognition", "growth"],
      actions: 2,
      summary: "Recognition gap named. Leadership write-up actioned.",
    },
    {
      date: "2026-05-20",
      durationMin: 30,
      reportShare: 53,
      areas: ["growth", "workload"],
      actions: 2,
      summary: "Cross-team lead opportunity identified for Q3.",
    },
  ],
};

// ---------------------------------------------------------------------------
// Noah Kim — Product Manager; eyeing a lead role; growth thread hot.
// ---------------------------------------------------------------------------
const noah: Person = {
  id: "p-noah",
  name: "Noah Kim",
  role: "Product Manager",
  pronouns: "he/him",
  initials: "NK",
  hue: 340,
  tenureMonths: 26,
  cadenceDays: 14,
  lastOneOnOne: "2026-05-28",
  nextScheduled: "2026-06-11",
  talkTrend: [58, 62, 70, 68, 72],
  sentimentTrend: [4, 4, 4, 5, 5],
  coverage: {
    growth: 6,
    feedback: 10,
    workload: 14,
    wellbeing: 20,
    relationships: 18,
    recognition: 26,
  },
  threads: [
    {
      id: "t-noah-1",
      title: "Targeting a Group PM or lead PM role",
      area: "growth",
      status: "open",
      priority: 90,
      lastTouched: "2026-05-28",
      note: "He's been explicit about wanting to lead a product area by end of year. Real ambition, real potential.",
      raise: true,
    },
    {
      id: "t-noah-2",
      title: "Cross-functional relationships with engineering leads",
      area: "relationships",
      status: "open",
      priority: 60,
      lastTouched: "2026-05-14",
      note: "He's PM-ing across two eng teams. Relationship health matters for his influence.",
      raise: false,
    },
    {
      id: "t-noah-3",
      title: "Roadmap prioritization under pressure from sales",
      area: "workload",
      status: "open",
      priority: 55,
      lastTouched: "2026-05-28",
      note: "Sales keeps asking for custom features. He's holding the line well but needs support.",
      raise: false,
    },
  ],
  actions: [
    {
      id: "a-noah-1",
      text: "Draft a 6-month plan toward a lead PM role with Noah",
      owner: "manager",
      status: "open",
      createdAt: "2026-05-28",
      fromArea: "growth",
      linkedThread: "t-noah-1",
    },
    {
      id: "a-noah-2",
      text: "Set up intro between Noah and the Eng leads from the platform pod",
      owner: "manager",
      status: "open",
      createdAt: "2026-05-14",
      fromArea: "relationships",
      linkedThread: "t-noah-2",
    },
    {
      id: "a-noah-3",
      text: "Write a one-pager on roadmap boundary setting for the sales conversation",
      owner: "report",
      status: "open",
      createdAt: "2026-05-28",
      fromArea: "workload",
    },
    {
      id: "a-noah-4",
      text: "Share roadmap context to align sales expectations",
      owner: "report",
      status: "done",
      createdAt: "2026-05-07",
      doneAt: "2026-05-13",
      fromArea: "workload",
    },
  ],
  asyncAgenda: [
    {
      id: "async-noah-1",
      text: "Really energized about the lead PM conversation. Want to make a plan while we have momentum.",
      area: "growth",
      mood: "energized",
      addedAt: "2026-06-01",
    },
    {
      id: "async-noah-2",
      text: "The sales pressure on the roadmap is getting louder. Need your help holding the line in the next exec review.",
      area: "workload",
      mood: "unsure",
      addedAt: "2026-06-02",
    },
  ],
  meetings: [
    {
      date: "2026-03-19",
      durationMin: 30,
      reportShare: 58,
      areas: ["workload", "relationships"],
      actions: 1,
      summary: "Roadmap framing. Cross-functional dynamics mentioned.",
    },
    {
      date: "2026-04-02",
      durationMin: 30,
      reportShare: 62,
      areas: ["growth", "feedback"],
      actions: 2,
      summary: "Lead PM ambition first named. Strong self-awareness.",
    },
    {
      date: "2026-04-23",
      durationMin: 30,
      reportShare: 70,
      areas: ["growth", "relationships"],
      actions: 2,
      summary: "Career plan outlined. Cross-team relationship building actioned.",
    },
    {
      date: "2026-05-14",
      durationMin: 30,
      reportShare: 68,
      areas: ["relationships", "workload"],
      actions: 2,
      summary: "Sales pressure surfaced. Eng lead intros planned.",
    },
    {
      date: "2026-05-28",
      durationMin: 30,
      reportShare: 72,
      areas: ["growth", "workload"],
      actions: 3,
      summary: "Concrete lead PM planning started. Strong session — high energy.",
    },
  ],
};

// ---------------------------------------------------------------------------
// Seed assembly
// ---------------------------------------------------------------------------

const PEOPLE: Person[] = [sofia, priya, tariq, maya, dev, noah];

export function seedData(): AppData {
  // Return fresh copies so callers can mutate safely.
  return structuredClone({ version: 2, people: PEOPLE, templates: TEMPLATES });
}
